version: '3.9'

services:

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: clinicscheduling-sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Developer123
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - clinicscheduling-network

  backend:
    build:
      context: ./ClinicScheduling.Api
      dockerfile: Dockerfile
    container_name: clinicscheduling-api
    depends_on:
      - sqlserver
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__ClinicSchedulingDb=Server=sqlserver,1433;Database=ClinicScheduling;User Id=sa;Password=Developer123;TrustServerCertificate=True;Encrypt=False
    ports:
      - "4444:8080"
    networks:
      - clinicscheduling-network

  frontend:
    build:
      context: ./ClinicScheduling.Frontend
      dockerfile: Dockerfile
    container_name: clinicscheduling-frontend
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://backend:8080
    ports:
      - "4445:80"
    networks:
      - clinicscheduling-network


volumes:
  sqlserver_data:


networks:
  clinicscheduling-network:
    driver: bridge
